version: '3.9'

services:
  web:
    build: .
    command: gunicorn llm.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    environment:
      - DEBUG=False
      - DJANGO_ALLOWED_HOSTS=mevzuat.life,www.mevzuat.life
    restart: always
    stdin_open: true
    tty: true
